In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt


In [2]:
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
out = transformer_model(src, tgt)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")


In [10]:
transformer_model.state_dict()

OrderedDict([('encoder.layers.0.self_attn.in_proj_weight',
              tensor([[-0.0274, -0.0459,  0.0361,  ..., -0.0028,  0.0415,  0.0477],
                      [-0.0107, -0.0270, -0.0272,  ..., -0.0071,  0.0064,  0.0216],
                      [ 0.0437, -0.0169, -0.0157,  ...,  0.0435, -0.0259, -0.0019],
                      ...,
                      [ 0.0385,  0.0230, -0.0055,  ..., -0.0100,  0.0102, -0.0203],
                      [ 0.0446, -0.0022,  0.0365,  ..., -0.0373,  0.0028, -0.0302],
                      [-0.0307,  0.0141,  0.0533,  ...,  0.0110,  0.0493,  0.0540]])),
             ('encoder.layers.0.self_attn.in_proj_bias',
              tensor([0., 0., 0.,  ..., 0., 0., 0.])),
             ('encoder.layers.0.self_attn.out_proj.weight',
              tensor([[ 0.0764, -0.0459, -0.0640,  ...,  0.0718,  0.0555, -0.0353],
                      [ 0.0058, -0.0561, -0.0359,  ..., -0.0106,  0.0418,  0.0339],
                      [-0.0411,  0.0712, -0.0081,  ..., -0.0665,  0

In [11]:
m = nn.Dropout(p=0.2)
input = torch.randn(20, 16)
output = m(input)

In [18]:
# FloatTensor containing pretrained weights
weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])
embedding = nn.Embedding.from_pretrained(weight)
# Get embeddings for index 1
input = torch.LongTensor([1])
embedding(input)

tensor([[1.0000, 2.3000, 3.0000]])

In [16]:
embedding.state_dict()

OrderedDict([('weight',
              tensor([[1.0000, 2.3000, 3.0000],
                      [4.0000, 5.1000, 6.3000]]))])